# ===============================================================================
# Ignytion IO - CRUCIBLE CORE
# Copyright (c) 2026 Ignytion IO. All rights reserved.
# File        : hw/protocols/i2c/01_rtl/Makefile
# Created     : 2026-09-21
# Description : Make entrypoint for the I2C RTL source stage.
# ===============================================================================

.PHONY: all rtl list

all: rtl

rtl: list

list:
	@printf '%s\n' i2c_core.v
