# ===============================================================================
# Ignytion IO - CRUCIBLE CORE
# Copyright (c) 2026 Ignytion IO. All rights reserved.
# File        : hw/core/01_rtl/Makefile
# Created     : 2026-09-21
# Description : Make entrypoint for the Core (full chip) RTL source stage.
# ===============================================================================

.PHONY: all rtl list

all: rtl

rtl: list

list:
	@printf '%s\n' protocol_emulator_top.v
