# ===============================================================================
# Ignytion IO - CRUCIBLE CORE
# Copyright (c) 2026 Ignytion IO. All rights reserved.
# File        : hw/protocols/stretch/usb_ls/01_rtl/Makefile
# Created     : 2026-09-21
# Description : Make entrypoint for the USB low-speed (stretch) RTL source stage.
# ===============================================================================

.PHONY: all rtl list

all: rtl

rtl: list

list:
	@printf '%s\n' usb_ls_core.v
